version: '3'
services:
    elasticsearch:
        image: elasticsearch:8.15.0
        container_name: elasticsearch
        restart: unless-stopped
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    kibana:
        image: kibana:8.15.0
        container_name: kibana
        restart: unless-stopped
        ports: 
            - 5601:5601
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
