version: '3.7'

networks:
  default:
    name: ch-net
    external: true

services:
  
  clickhouse-server:
    image: yandex/clickhouse-server
    container_name: clickhouse-server
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - ./users.xml:/etc/clickhouse-server/users.xml
      - ./db_back:/var/lib/clickhouse
      - ./config.xml:/etc/clickhouse-server/config.xml
    ulimits:
      nofile: 262144
