version: '3'

services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    ports:
      - "9042:9042"
      - "7199:7199" # JMX
      # - "7000:7000" # cluster communication
      # - "7001:7001" # cluster communication (SSL)

    volumes:
      - ./data/cassandra1:/var/lib/cassandra
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
    networks:
      - cassandra-network

  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
    networks:
      - cassandra-network
    volumes:
      - ./data/cassandra2:/var/lib/cassandra
      
  cassandra3:
    image: cassandra:latest
    container_name: cassandra3
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
    networks:
      - cassandra-network
    volumes:
      - ./data/cassandra3:/var/lib/cassandra

networks:
  cassandra-network: