version: '3.3'

services:
  redis:
    image: redis:7.2.5
    container_name: otus-redis-7.2
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./d–∞ta:/root/redis
      - ./redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    # environment:
    #   - REDIS_PASSWORD=my-password
    #   - REDIS_PORT=6379
    #   - REDIS_DATABASES=16